# Book settings

# Learn more at https://jupyterbook.org/customize/config.html

title: Group 12 Final Project
author: Group 12
copyright: "2023"
logo: logo.jpg

execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


# Information about where the book exists on the web
repository:
  url: https://github.com/UCB-stat-159-s23/project-Group12
  branch: HEAD  
  
html:
  use_repository_button : true
  use_issues_button     : true

launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"